require 'spec_helper'
describe WundergroundApi 
	json_response = '
		{
	  "response":{
	    "version":"0.1",
	    "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
	    "features":{
	      "almanac":1,
	      "forecast":1
	    }
	  },
	  "forecast":{
	    "txt_forecast":{
	      "date":"8:00 AM PDT",
	      "forecastday":[
	        {
	          "period":0,
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "title":"Wednesday",
	          "fcttext":"Clear. High of 72F. Breezy. Winds from the WNW at 10 to 20 mph.",
	          "fcttext_metric":"Clear. High of 22C. Windy. Winds from the WNW at 15 to 30 km/h.",
	          "pop":"10"
	        },
	        {
	          "period":1,
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "title":"Wednesday Night",
	          "fcttext":"Clear. Low of 55F. Winds from the NW at 5 to 15 mph.",
	          "fcttext_metric":"Clear. Low of 13C. Breezy. Winds from the NW at 10 to 20 km/h.",
	          "pop":"0"
	        },
	        {
	          "period":2,
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "title":"Thursday",
	          "fcttext":"Clear. High of 79F. Winds from the NNW at 10 to 15 mph shifting to the WNW in the afternoon.",
	          "fcttext_metric":"Clear. High of 26C. Breezy. Winds from the NNW at 20 to 25 km/h shifting to the WNW in the afternoon.",
	          "pop":"0"
	        },
	        {
	          "period":3,
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "title":"Thursday Night",
	          "fcttext":"Clear. Low of 55F. Winds from the NW at 5 to 20 mph.",
	          "fcttext_metric":"Clear. Low of 13C. Breezy. Winds from the NW at 10 to 25 km/h.",
	          "pop":"0"
	        },
	        {
	          "period":4,
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "title":"Friday",
	          "fcttext":"Clear. High of 82F. Winds from the NNW at 5 to 10 mph.",
	          "fcttext_metric":"Clear. High of 28C. Winds from the NNW at 10 to 15 km/h.",
	          "pop":"0"
	        },
	        {
	          "period":5,
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "title":"Friday Night",
	          "fcttext":"Clear. Low of 55F. Winds less than 5 mph.",
	          "fcttext_metric":"Clear. Low of 13C. Winds less than 5 km/h.",
	          "pop":"0"
	        },
	        {
	          "period":6,
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "title":"Saturday",
	          "fcttext":"Clear in the morning, then partly cloudy. High of 73F. Winds less than 5 mph.",
	          "fcttext_metric":"Clear in the morning, then partly cloudy. High of 23C. Winds less than 5 km/h.",
	          "pop":"0"
	        },
	        {
	          "period":7,
	          "icon":"mostlycloudy",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/mostlycloudy.gif",
	          "title":"Saturday Night",
	          "fcttext":"Overcast. Low of 54F. Winds less than 5 mph.",
	          "fcttext_metric":"Overcast. Low of 12C. Winds less than 5 km/h.",
	          "pop":"0"
	        }
	      ]
	    },
	    "simpleforecast":{
	      "forecastday":[
	        {
	          "date":{
	            "epoch":"1380175200",
	            "pretty":"11:00 PM PDT on September 25, 2013",
	            "day":25,
	            "month":9,
	            "year":2013,
	            "yday":267,
	            "hour":23,
	            "min":"00",
	            "sec":0,
	            "isdst":"1",
	            "monthname":"September",
	            "weekday_short":"Wed",
	            "weekday":"Wednesday",
	            "ampm":"PM",
	            "tz_short":"PDT",
	            "tz_long":"America/Los_Angeles"
	          },
	          "period":1,
	          "high":{
	            "fahrenheit":"72",
	            "celsius":"22"
	          },
	          "low":{
	            "fahrenheit":"55",
	            "celsius":"13"
	          },
	          "conditions":"Clear",
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "skyicon":"sunny",
	          "pop":10,
	          "qpf_allday":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "qpf_day":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "qpf_night":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "snow_allday":{
	            "in":0,
	            "cm":0
	          },
	          "snow_day":{
	            "in":0,
	            "cm":0
	          },
	          "snow_night":{
	            "in":0,
	            "cm":0
	          },
	          "maxwind":{
	            "mph":19,
	            "kph":30,
	            "dir":"WNW",
	            "degrees":285
	          },
	          "avewind":{
	            "mph":16,
	            "kph":26,
	            "dir":"WNW",
	            "degrees":290
	          },
	          "avehumidity":67,
	          "maxhumidity":84,
	          "minhumidity":49
	        },
	        {
	          "date":{
	            "epoch":"1380261600",
	            "pretty":"11:00 PM PDT on September 26, 2013",
	            "day":26,
	            "month":9,
	            "year":2013,
	            "yday":268,
	            "hour":23,
	            "min":"00",
	            "sec":0,
	            "isdst":"1",
	            "monthname":"September",
	            "weekday_short":"Thu",
	            "weekday":"Thursday",
	            "ampm":"PM",
	            "tz_short":"PDT",
	            "tz_long":"America/Los_Angeles"
	          },
	          "period":2,
	          "high":{
	            "fahrenheit":"79",
	            "celsius":"26"
	          },
	          "low":{
	            "fahrenheit":"55",
	            "celsius":"13"
	          },
	          "conditions":"Clear",
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "skyicon":"sunny",
	          "pop":0,
	          "qpf_allday":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "qpf_day":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "qpf_night":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "snow_allday":{
	            "in":0,
	            "cm":0
	          },
	          "snow_day":{
	            "in":0,
	            "cm":0
	          },
	          "snow_night":{
	            "in":0,
	            "cm":0
	          },
	          "maxwind":{
	            "mph":15,
	            "kph":24,
	            "dir":"WNW",
	            "degrees":287
	          },
	          "avewind":{
	            "mph":13,
	            "kph":21,
	            "dir":"WNW",
	            "degrees":301
	          },
	          "avehumidity":56,
	          "maxhumidity":76,
	          "minhumidity":31
	        },
	        {
	          "date":{
	            "epoch":"1380348000",
	            "pretty":"11:00 PM PDT on September 27, 2013",
	            "day":27,
	            "month":9,
	            "year":2013,
	            "yday":269,
	            "hour":23,
	            "min":"00",
	            "sec":0,
	            "isdst":"1",
	            "monthname":"September",
	            "weekday_short":"Fri",
	            "weekday":"Friday",
	            "ampm":"PM",
	            "tz_short":"PDT",
	            "tz_long":"America/Los_Angeles"
	          },
	          "period":3,
	          "high":{
	            "fahrenheit":"82",
	            "celsius":"28"
	          },
	          "low":{
	            "fahrenheit":"55",
	            "celsius":"13"
	          },
	          "conditions":"Clear",
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "skyicon":"sunny",
	          "pop":0,
	          "qpf_allday":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "qpf_day":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "qpf_night":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "snow_allday":{
	            "in":0,
	            "cm":0
	          },
	          "snow_day":{
	            "in":0,
	            "cm":0
	          },
	          "snow_night":{
	            "in":0,
	            "cm":0
	          },
	          "maxwind":{
	            "mph":8,
	            "kph":13,
	            "dir":"West",
	            "degrees":278
	          },
	          "avewind":{
	            "mph":7,
	            "kph":11,
	            "dir":"South",
	            "degrees":186
	          },
	          "avehumidity":52,
	          "maxhumidity":69,
	          "minhumidity":25
	        },
	        {
	          "date":{
	            "epoch":"1380434400",
	            "pretty":"11:00 PM PDT on September 28, 2013",
	            "day":28,
	            "month":9,
	            "year":2013,
	            "yday":270,
	            "hour":23,
	            "min":"00",
	            "sec":0,
	            "isdst":"1",
	            "monthname":"September",
	            "weekday_short":"Sat",
	            "weekday":"Saturday",
	            "ampm":"PM",
	            "tz_short":"PDT",
	            "tz_long":"America/Los_Angeles"
	          },
	          "period":4,
	          "high":{
	            "fahrenheit":"73",
	            "celsius":"23"
	          },
	          "low":{
	            "fahrenheit":"54",
	            "celsius":"12"
	          },
	          "conditions":"Clear",
	          "icon":"clear",
	          "icon_url":"http://icons-ak.wxug.com/i/c/k/clear.gif",
	          "skyicon":"mostlysunny",
	          "pop":0,
	          "qpf_allday":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "qpf_day":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "qpf_night":{
	            "in":0.00,
	            "mm":0.0
	          },
	          "snow_allday":{
	            "in":0,
	            "cm":0
	          },
	          "snow_day":{
	            "in":0,
	            "cm":0
	          },
	          "snow_night":{
	            "in":0,
	            "cm":0
	          },
	          "maxwind":{
	            "mph":8,
	            "kph":13,
	            "dir":"WSW",
	            "degrees":256
	          },
	          "avewind":{
	            "mph":5,
	            "kph":8,
	            "dir":"SW",
	            "degrees":229
	          },
	          "avehumidity":64,
	          "maxhumidity":77,
	          "minhumidity":31
	        }
	      ]
	    }
	  },
	  "almanac":{
	    "airport_code":"KSFO",
	    "temp_high":{
	      "normal":{
	        "F":"73",
	        "C":"23"
	      },
	      "record":{
	        "F":"91",
	        "C":"32"
	      },
	      "recordyear":"1960"
	    },
	    "temp_low":{
	      "normal":{
	        "F":"55",
	        "C":"13"
	      },
	      "record":{
	        "F":"47",
	        "C":"8"
	      },
	      "recordyear":"1972"
	    }
	  }
	}
	'
end